
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "uid": "amans584",
    "username": "Aman Singh",
    "email": "amans584@gmail.com",
    "password": "lol"
}

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "uid": "amans584",
    "password": "lol"
}

###

POST http://localhost:5000/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJhbWFuczU4NCIsInVzZXJuYW1lIjoiQW1hbiBTaW5naCIsImVtYWlsIjoiYW1hbnM1ODRAZ21haWwuY29tIiwiaWF0IjoxNzE2NDk0OTg1LCJleHAiOjE3MTY2Njc3ODV9.eW4hFFtu7oXpfrn8hfUNkU18l17iWrlNvJj4YpM2QEs

###

POST http://localhost:5000/auth/refresh
Content-Type: application/json

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJhbWFuczU4NCIsInVzZXJuYW1lIjoiQW1hbiBTaW5naCIsImVtYWlsIjoiYW1hbnM1ODRAZ21haWwuY29tIiwiaWF0IjoxNzE2NDk1MDAxfQ.sPkas8L-SULuxhXEJ4QjiBlJ4P_zdrnt0GOMha1lvT0"
}