POST http://localhost:5000/comments/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJhbWFuczU4NCIsInVzZXJuYW1lIjoiQW1hbiBTaW5naCIsImVtYWlsIjoiYW1hbnM1ODRAZ21haWwuY29tIiwiaWF0IjoxNzE2NDk1MDgwLCJleHAiOjE3MTY2Njc4ODB9.7iLfpS33Tp_TBPNhTy5lzffiSciylxDuJ8ahYoXEDFM

{
    "pid": "b7cee206-c5bc-4465-9ae6-3fa6761ca5f5",
    "content": "Nice Post"
}

### 

GET http://localhost:5000/comments/getComments/78662b0b-22b2-4f9b-a36e-9da4c3c38460
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJrdXNoMjcwOSIsImVtYWlsIjoia3VzaEBnbWFpbC5jb20iLCJpYXQiOjE3MTYwMTE5MTcsImV4cCI6MTcxNjAxMzcxN30.DOAtomisTmE7wwhLuLVme-Tu1BIy283DVEquyZ0gX-s

### 

DELETE  http://localhost:5000/comments/delete/a0c729ef-948f-496f-82f6-3c4ffb5e58b0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJrdXNoMjcwOSIsImVtYWlsIjoia3VzaEBnbWFpbC5jb20iLCJpYXQiOjE3MTYwMTE5MTcsImV4cCI6MTcxNjAxMzcxN30.DOAtomisTmE7wwhLuLVme-Tu1BIy283DVEquyZ0gX-s